In [1]:
import numpy as np

In [2]:
u_matrix = np.random.rand(10,3)*10
np.linalg.norm(u_matrix, ord=2, axis=1)
np.linalg.norm(u_matrix, ord=2, axis=1, keepdims=True)

array([[  7.01755598],
       [ 13.205407  ],
       [ 13.44413371],
       [ 10.16360456],
       [  8.51559406],
       [  8.31092944],
       [ 10.33261711],
       [  7.80340679],
       [  7.72235143],
       [ 10.59529205]])

In [3]:
i_values = np.random.permutation(np.array(range(10)))
i_values

array([0, 5, 2, 3, 7, 8, 1, 4, 6, 9])

In [4]:
np.dot([1,2,3], 3)

array([3, 6, 9])

In [5]:
np.random.permutation(np.arange(10))

array([6, 4, 0, 5, 1, 2, 3, 9, 8, 7])

In [6]:
from sklearn.datasets.mldata import fetch_mldata

In [7]:
data = fetch_mldata('iris')

In [8]:
data.data

array([[ -5.55556000e-01,   2.50000000e-01,  -8.64407000e-01,
         -9.16667000e-01],
       [ -6.66667000e-01,  -1.66667000e-01,  -8.64407000e-01,
         -9.16667000e-01],
       [ -7.77778000e-01,   0.00000000e+00,  -8.98305000e-01,
         -9.16667000e-01],
       [ -8.33333000e-01,  -8.33334000e-02,  -8.30508000e-01,
         -9.16667000e-01],
       [ -6.11111000e-01,   3.33333000e-01,  -8.64407000e-01,
         -9.16667000e-01],
       [ -3.88889000e-01,   5.83333000e-01,  -7.62712000e-01,
         -7.50000000e-01],
       [ -8.33333000e-01,   1.66667000e-01,  -8.64407000e-01,
         -8.33333000e-01],
       [ -6.11111000e-01,   1.66667000e-01,  -8.30508000e-01,
         -9.16667000e-01],
       [ -9.44444000e-01,  -2.50000000e-01,  -8.64407000e-01,
         -9.16667000e-01],
       [ -6.66667000e-01,  -8.33334000e-02,  -8.30508000e-01,
         -1.00000000e+00],
       [ -3.88889000e-01,   4.16667000e-01,  -8.30508000e-01,
         -9.16667000e-01],
       [ -7.22222000e

In [9]:
data.target - 1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from sklearn.metrics.cluster import normalized_mutual_info_score

In [11]:
normalized_mutual_info_score(data.target, data.target-1)

1.0

In [12]:
pred = data.target.copy()

pred[3] = 2

In [13]:
# data.target

In [14]:
pred

array([1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [15]:
normalized_mutual_info_score(data.target, pred)

0.97019115724260474